<hr>
<center> Coding Exercise for Control Systems<br>
<b> Exercise 2: Solutions to LTI Systems & Internal Stability </b> <br>
Prof. Dr. Florian Dörfler <br>
Automatic Control Laboratory, ETH Zurich </center>
<hr>

In this notebook, we learn about solutions to LTI systems and internal stability.

<blockquote>
<b>Activity:</b> Execute the code cells below so that the necessary libraries get imported.
</blockquote>

In [ ]:
!pip install control

In [1]:
import numpy as np # the standard library for numerics, vectors, matrices
import control as ct # the standard library for basic operations for analysis and design of feedback control systems
import matplotlib.pyplot as plt # a comprehensive library for creating static, animated, and interactive visualizations
import scipy.linalg as slin # a library for linear algebra functions

<br>

<b> C 2.1: Stability of Continuous-Time and Discrete-Time LTI Systems </b>

Consider the continuous-time linear time-invariant system
\begin{equation}
\dot{x}(t) = Ax(t)=\begin{bmatrix} -3& 4& 5\\ 1&-1&-2\\0&3&-2\end{bmatrix} x(t).
\end{equation}

<blockquote>
<b>Activity:</b> Complete the code fragment below to determine if the origin of the continuous-time time system is stable.
</blockquote>

In [ ]:
# TODO: toggle
#system matrix
A = ...

#check stability of the system
...

<i> Answer on system stability</i>:  . . .

<blockquote>
<b>Solution:</b> You can check your answer with the solution by clicking on the "..." below.
</blockquote>

In [2]:
# TODO: toggle
#system matrix
A = np.array([[-3,4,5],[1, -1,-2],[0,3,-2]])

#check stability of the system
e,v = np.linalg.eig(A)
e

array([-0.07982488+0.j        , -2.96008756+1.94043922j,
       -2.96008756-1.94043922j])

<i> Answer on system stability</i>: Since the real part of all eigenvalues of the system matrix is $<0$, we can conclude that the continuous-time system is asymptotically stable.

Next, we will discretize the above continuous-time system using the sample-hold approach, i.e., we determine the system 
\begin{equation}
x_{k+1} = A_\mathrm{d}x_k
\end{equation}

<blockquote>
<b>Activity:</b> What can you say about the stability of the discretized system, given your knowledge on the stability of the continuous-time system?
</blockquote>

<i> Answer on system stability: . . .  </i>

<blockquote>
<b>Solution:</b> You can check your answer with the solution by clicking on the "..." below.
</blockquote>

<i> Answer on system stability</i>: Since the continuous-time system is asymptotically stable, it follows that the discretized system using sample-hold discretization is asymptotically stable as well.

><b>Activity:</b> Complete the code fragment below and calculate the matrix exponential $e^{AT}$ to discretize the continuous-time system using the sample hold approach, i.e., calculate the discrete-time matrix $A_\mathrm{d}=e^{AT}$. Consider $T=1$.


In [1]:
#matrix exponential
eA = ...

#discrete-time system matrix A_d
A_d = ...
A_d

Ellipsis

<blockquote>
<b>Solution:</b> You can check your answer with the solution by clicking on the "..." below.
</blockquote>

In [3]:
# TODO: toggle
#matrix exponential
eA = slin.expm(A)

#discrete-time system matrix A_d
A_d = eA
A_d

array([[ 0.54071052,  1.73613129, -0.12077122],
       [ 0.16344991,  0.43467768, -0.11043349],
       [ 0.21646633,  0.70681606, -0.08954944]])

<blockquote>
<b>Activity:</b> Complete the code fragment below and check your stability hypothesis of the discretized system numerically.
</blockquote>

In [ ]:
#check stability of the discretized system
...

<blockquote>
<b>Solution:</b> You can check your answer with the solution by clicking on the "..." below.
</blockquote>

In [4]:
# TODO: toggle
#check stability of the discretized system
e,v = np.linalg.eig(A_d)
abs(e[0]), abs(e[1]), abs(e[2])

(np.float64(0.9232780179204737),
 np.float64(0.051814380072072196),
 np.float64(0.051814380072072196))

<br>

<b> C 2.2: Discretization of Continuous-Time System </b>

Consider the continuous-time linear time-invariant system 
\begin{equation}
\dot{x}(t) = \begin{bmatrix} -2& -6 \\ 0& -1\end{bmatrix} x(t)+\begin{bmatrix} 1\\0\end{bmatrix}u(t),\\
y(t) = \begin{bmatrix}1&0 \end{bmatrix}x(t)+u(t).
\end{equation}

><b>Activity:</b> Complete the code fragment below to compute and discretize the continuous-time system using the sample-hold approach with a sampling time of $T=0.1$ seconds.

In [ ]:
#system matrices
A = ...
B = ...
C = ...
D = ...

#sampling time [sec]
T_s = ...

#build a continuous-time state-space object and discretize it
sys_ct = ...
sys_dt = ...
sys_dt

<blockquote>
<b>Solution:</b> You can check your answer with the solution by clicking on the "..." below.
</blockquote>

In [5]:
# TODO: toggle
#system matrices
A = np.array([[-2, -6],[0, -1]])
B = np.array([[1],[0]])
C = np.array([[1,0]])
D = np.array([1])

#sampling time [sec]
T_s = 0.1

#build a continuous-time state-space object and discretize it
sys_ct = ct.ss(A,B,C,D)
sys_dt = ct.StateSpace.sample(sys_ct,T_s,method='zoh')
sys_dt

StateSpace(
array([[ 0.81873075, -0.51663999],
       [ 0.        ,  0.90483742]]),
array([[0.09063462],
       [0.        ]]),
array([[1., 0.]]),
array([[1.]]),
dt=0.1,
name='sys[0]$sampled', states=2, outputs=1, inputs=1)

><b>Activity:</b> Let $x_0 = \begin{bmatrix}0&0\end{bmatrix}^T$ and $u_k=1,\,\forall k \geq 0$. Complete the code fragment below to compute and calculate $y_2$ (output of the discretized system at $k=2$) by simulating the discrete-time system of the previous activity.


In [ ]:
#initial state, input and discrete time steps
x0 = ...
U = ...
T = ...

#compute state and output evolution
t, y = ...

<blockquote>
<b>Solution:</b> You can check your answer with the solution by clicking on the "..." below.
</blockquote>

In [6]:
# TODO: toggle
#initial state and input
x0 = np.array([[0],[0]])
U = np.array([[1, 1, 1]])
T = np.array([0, 0.1, 0.2])

#compute state and output evolution
t, y = ct.forced_response(sys_dt,T=T,U=U,X0=x0)
y[2]

np.float64(1.1648399769821802)

<br>