<hr>
<center> Coding Exercise for Control Systems<br>
<b> Exercise 3: State-Space Control Systems </b> <br>
Prof. Dr. Florian Dörfler <br>
Automatic Control Laboratory, ETH Zurich </center>
<hr>

In this notebook, we learn about controllability of LTI systems.

<blockquote>
<b>Activity:</b> Execute the code cells below so that the necessary libraries get imported.
</blockquote>

In [ ]:
!pip install control

In [1]:
import numpy as np # the standard library for numerics, vectors, matrices
import control as ct # the standard library for basic operations for analysis and design of feedback control systems
import matplotlib.pyplot as plt # a comprehensive library for creating static, animated, and interactive visualizations
import scipy.linalg as slin # a library for linear algebra functions

<b> C 3.1: Analyzing controllability and uncontrollable subspaces </b>

Consider the continuous-time linear time-invariant system
\begin{equation}
\dot{x}(t) = Ax(t) + B u(t)=\begin{bmatrix} -1 & 2 & -3 & 0 \\ 0 & -2 & 6 & 4 \\ 0 & 0 & -4 & 4 \\ 0 & 0 & 0 & -6  \end{bmatrix} x(t) + \begin{bmatrix} 0 \\ 1 \\ 0 \\ 0 \end{bmatrix} u(t).
\end{equation}

<blockquote>
<b>Activity:</b> Complete the code fragment below to determine if the system is controllable.
</blockquote>

In [4]:
# your code goes here

<blockquote>
<b>Solution:</b> You can check your answer with the solution by clicking on the "..." below.
</blockquote>

In [2]:
A = np.array([[-1, 2, -3, 0],[0, -2, 6, 4],[0, 0, -4, 4],[0, 0, 0, -6]])
B = np.array([[0],[1],[0],[0]])
W_c = ct.ctrb(A,B)
np.linalg.matrix_rank(W_c)
# given that the rank is only 2 the system is not controllable

np.int64(2)

Next, we want to bring the system to the controllability staircase form to find out which states are controllable and which ones are not.

<blockquote>
<b>Activity:</b>  Derive a transformation matrix $T$ with which you can bring the system to a controllability staircase form.
</blockquote>

In [6]:
# your code goes here

<blockquote>
<b>Solution:</b> You can check your answer with the solution by clicking on the "..." below.
</blockquote>

In [3]:
print(W_c)
T1 = W_c[:,0:np.linalg.matrix_rank(W_c)]
print(T1)
T2 = np.array([[0, 0],[0, 0],[1, 0],[0, 1]])
print(T2)
T = np.hstack((T1,T2))
print(T)

[[ 0.  2. -6. 14.]
 [ 1. -2.  4. -8.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0.  2.]
 [ 1. -2.]
 [ 0.  0.]
 [ 0.  0.]]
[[0 0]
 [0 0]
 [1 0]
 [0 1]]
[[ 0.  2.  0.  0.]
 [ 1. -2.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


<blockquote>
<b>Activity:</b> Bring the system to the controllability staircase form. Is the system stabilizable?
</blockquote>

In [8]:
# your code goes here

<blockquote>
<b>Solution:</b> You can check your answer with the solution by clicking on the "..." below.
</blockquote>

In [4]:
A_scf = np.dot(np.dot(np.linalg.inv(T),A),T)
B_scf = np.dot(np.linalg.inv(T), B)
print(A_scf)
print(B_scf)
A_unc = A_scf[2:4,2:4]
np.linalg.eig(A_unc)
# The eigenvalues are negative. Therefore the uncontrollable subspace is stable and all uncontrollable states decay to zero. 
# That means the system is stabilizable. Note, that we could have also calculated the eigenvalues of A 
# which are all negative which means the system has to be stabilizable.

[[ 0.  -2.   3.   4. ]
 [ 1.  -3.  -1.5  0. ]
 [ 0.   0.  -4.   4. ]
 [ 0.   0.   0.  -6. ]]
[[1.]
 [0.]
 [0.]
 [0.]]


EigResult(eigenvalues=array([-4., -6.]), eigenvectors=array([[ 1.        , -0.89442719],
       [ 0.        ,  0.4472136 ]]))